// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjceenmkqpyjntndqikg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqY2Vlbm1rcXB5am50bmRxaWtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1NDg3OTUsImV4cCI6MjA1NTEyNDc5NX0._nmqkD-wyahe42Q2gkVHqn_d3z0j5tXZzmtfZqt-BcQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);